### ISSUE TITLE
Add to flathub?

### ISSUE THREAD

**Issue by nedrichards** [theunknownxy/openspades-flatpak#1]
Hey there, this looks pretty cool. [Flathub](https://flathub.org/) can easily host this if you wish and give access to distribution, builds for x86 and ARM, free bandwidth etc.

I'm not sure if the extra data is cross platform friendly, otherwise you'd probably have to disable ARM but  other than that it looks like you already comply with the rest of the [review guidelines](https://github.com/flathub/flathub/wiki/Review-Guidelines).

**Comment by jschlumpp** [comment]
Whoops I didn't get a notification for this issue. Sorry about that. But there is now an issue about flatpak in the upstream repo: yvt/openspades#788.
